export class AppStorageName {
  // 用户数据
  static readonly USER = "user"
  // 用户token
  static readonly TOKEN = "token"
  // app启动跳转url
  static readonly APP_WANT_URI = "appHasWantUri"
  // 路由栈
  static readonly NavPathStack = "NavPathStack"
  // windowStage
  static readonly WINDOW_STAGE = "windowStage"
  static readonly topRectHeight = "topRectHeight"
  static readonly bottomRectHeight = "bottomRectHeight"
  static readonly windowWidth = "windowWidth"
  static readonly windowHeight = "windowHeight"
  static readonly keyboardHeight = "keyboardHeight"
}

