/**
 * AppStorage name
 */
export class AppStorageName {
  // 用户数据
  static readonly USER = "user"
  // 用户token
  static readonly TOKEN = "token"
  // app启动跳转url
  static readonly APP_WANT_URI = "appHasWantUri"
  // 路由栈
  static readonly NavPathStack = "NavPathStack"
  // windowStage
  static readonly WINDOW_STAGE = "windowStage"
  // 顶部安全区
  static readonly topRectHeight = "topRectHeight"
  // 底部安全区
  static readonly bottomRectHeight = "bottomRectHeight"
  // 屏幕宽度
  static readonly windowWidth = "windowWidth"
  // 屏幕高度
  static readonly windowHeight = "windowHeight"
  // 键盘高度
  static readonly keyboardHeight = "keyboardHeight"
}

